
CREATE SEQUENCE IF NOT EXISTS PRODUTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS PRODUTO (
	ID NUMERIC(11) PRIMARY KEY,
	NOME VARCHAR ( 30 ),
	VALOR NUMERIC(11,2)
);

CREATE SEQUENCE IF NOT EXISTS VENDEDOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS VENDEDOR (
	ID NUMERIC(11) PRIMARY KEY,
	NOME VARCHAR ( 30 ),
	TELEFONE VARCHAR ( 30 )
);

CREATE SEQUENCE IF NOT EXISTS CLIENTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS CLIENTE (
	ID NUMERIC(11) PRIMARY KEY,
	NOME VARCHAR ( 30 ),
	TELEFONE VARCHAR ( 30 )
);

CREATE SEQUENCE IF NOT EXISTS VENDA_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS VENDA (
	ID NUMERIC(11) PRIMARY KEY,
	DATA_VENDA DATE,
	CLIENTE_ID NUMERIC(11),
	VENDEDOR_ID NUMERIC(11),
	TOTAL NUMERIC(11,2)
);

CREATE SEQUENCE IF NOT EXISTS ITEM_VENDA_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS ITEM_VENDA (
	ID NUMERIC(11) PRIMARY KEY,
	PRODUTO_ID NUMERIC(11),
	QUANTIDADE NUMERIC(11),
	VALOR_UN NUMERIC(11,2),
	TOTAL NUMERIC(11,2)
);

CREATE TABLE IF NOT EXISTS VENDA_ITENS (
  VENDA_ID NUMERIC(11),
  ITENS_ID NUMERIC(11)
);
