INSERT INTO PRODUTO (ID, NOME, VALOR) VALUES(NEXTVAL('PRODUTO_SEQ'),'CAMISETA', 17.99);
INSERT INTO PRODUTO (ID, NOME, VALOR) VALUES(NEXTVAL('PRODUTO_SEQ'),'TENIS', 250.00);
INSERT INTO PRODUTO (ID, NOME, VALOR) VALUES(NEXTVAL('PRODUTO_SEQ'),'MEIA', 5.99);
INSERT INTO PRODUTO (ID, NOME, VALOR) VALUES(NEXTVAL('PRODUTO_SEQ'),'SHORTS', 29.99);
INSERT INTO PRODUTO (ID, NOME, VALOR) VALUES(NEXTVAL('PRODUTO_SEQ'),'CALCA', 59.99);

INSERT INTO VENDEDOR (ID, NOME, TELEFONE) VALUES(NEXTVAL('VENDEDOR_SEQ'),'ADEMIR', '011-2360-0852');
INSERT INTO VENDEDOR (ID, NOME, TELEFONE) VALUES(NEXTVAL('VENDEDOR_SEQ'),'CELSO', '011-2352-7741');
INSERT INTO VENDEDOR (ID, NOME, TELEFONE) VALUES(NEXTVAL('VENDEDOR_SEQ'),'SERGIO', '012-99553-4440');
INSERT INTO VENDEDOR (ID, NOME, TELEFONE) VALUES(NEXTVAL('VENDEDOR_SEQ'),'SONIA', '012-2350-8585');
INSERT INTO VENDEDOR (ID, NOME, TELEFONE) VALUES(NEXTVAL('VENDEDOR_SEQ'),'MARIA', '011-2365-5686');

INSERT INTO CLIENTE (ID, NOME, TELEFONE) VALUES(NEXTVAL('CLIENTE_SEQ'),'SORAIA', '011-2360-0852');
INSERT INTO CLIENTE (ID, NOME, TELEFONE) VALUES(NEXTVAL('CLIENTE_SEQ'),'MARIELLE', '011-2352-7741');
INSERT INTO CLIENTE (ID, NOME, TELEFONE) VALUES(NEXTVAL('CLIENTE_SEQ'),'BRUNO', '012-99553-4440');
INSERT INTO CLIENTE (ID, NOME, TELEFONE) VALUES(NEXTVAL('CLIENTE_SEQ'),'MANUELA', '012-2350-8585');
INSERT INTO CLIENTE (ID, NOME, TELEFONE) VALUES(NEXTVAL('CLIENTE_SEQ'),'DANIEL', '011-2365-5686');
